name: Data Analyzer

on:
 
  push:
    paths:
      "Data.csv"

  workflow_dispatch:

jobs:

  Run_R_Script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install R Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::ggplot2

      - name: Check files in directory
        run: |
         ls

      - name: Run R script
        run: Rscript data_analysis_R_script.R

      - name: Check files in directory again
        run: ls


      - name: Commit changes
        run: |
          git config --global user.name "DanielBrett"
          git config --global user.email "dbrett@brocku.ca"
          git add .
          git commit -m "Pet Data Analyzer was activated"
          git push
